dist : trusty
language: node_js
node_js :
 - "6.0"
before_script:
    - npm install -g angular-cli    
    - npm install
    - npm install -g firebase-tools
    - ng build --prod
script:
  - echo "Deploying!"
# install:
#     - npm install
#     - npm install -g firebase-tools
after_success:
    - firebase deploy --token $FIREBASE_TOKEN